version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "19:00"
    open-pull-requests-limit: 300
    assignees: 
    - luke-h1
