version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "7:30"
    open-pull-requests-limit: 1000
    assignees: 
    - luke-h1
