export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST';
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS';
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL';

export const PROPERTY_DELETE_REQUEST = 'PROPERTY_DELETE_REQUEST';
export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS';
export const PROPERTY_DELETE_FAIL = 'PROPERTY_DELETE_FAIL';

export const PROPERTY_CREATE_REQUEST = 'PROPERTY_CREATE_REQUEST';
export const PROPERTY_CREATE_SUCCESS = 'PROPERTY_CREATE_SUCCESS';
export const PROPERTY_CREATE_FAIL = 'PROPERTY_CREATE_FAIL';
export const PROPERTY_CREATE_RESET = 'PROPERTY_CREATE_RESET';

export const PROPERTY_UPDATE_REQUEST = 'PROPERTY_UPDATE_REQUEST';
export const PROPERTY_UPDATE_SUCCESS = 'PROPERTY_UPDATE_SUCCESS';
export const PROPERTY_UPDATE_FAIL = 'PROPERTY_UPDATE_FAIL';
export const PROPERTY_UPDATE_RESET = 'PROPERTY_UPDATE_RESET';

export const PROPERTY_CREATE_REVIEW_REQUEST = 'PROPERTY_CREATE_REVIEW_REQUEST';
export const PROPERTY_CREATE_REVIEW_SUCCESS = 'PROPERTY_CREATE_REVIEW_SUCCESS';
export const PROPERTY_CREATE_REVIEW_FAIL = 'PROPERTY_CREATE_REVIEW_FAIL';
export const PROPERTY_CREATE_REVIEW_RESET = 'PROPERTY_CREATE_REVIEW_RESET';

export const PROPERTY_TOP_REQUEST = 'PROPERTY_TOP_REQUEST';
export const PROPERTY_TOP_SUCCESS = 'PROPERTY_TOP_SUCCESS';
export const PROPERTY_TOP_FAIL = 'PROPERTY_TOP_FAIL';
