name: CI / build (push / pull)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: luke-h1/checkout@v2.3.4

      - name: Use (Volta) Node.js ${{ matrix.node-version }}
        uses: luke-h1/action@v1.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: bootstrap
        run: npm run bootstrap

      - name: bootstrap:prod
        run: npm run bootstrap:prod

      - name: format
        run: npm run format

      - name: lint
        run: npm run lint

      - name: build backend
        run: cd packages/abb-server && npm run build 

      - name: build web
        run: cd packages/abb-web && npm run build 

      - name: build app
        run: cd packages/abb-app && npm run build
